context:
  name: altair-aitools-runtime
  version: 1.2
  python_min: "3.12"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://maven.rapidminer.com/repository/pypi-snapshot/packages/altair-aitools-runtime/${{ version }}/altair_aitools_runtime-${{ version }}.tar.gz
  sha256: 972d79e683f4beb73e0acaee41f5d487e58a36041d6814853fee4a080e0f0512

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
  - python ==${{ python_min }}
  - hatchling
  - pip
  run:
  - rapidminer-ai-runtime 2.0.*

tests:
  - python:
      imports:
        - altair_aitools.ext
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  summary: altair-aitools-runtime is a comprehensive package that provides a set of tools to run Altair RapidMiner AI tools extensions in Python.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://altair.com/altair-rapidminer

extra:
  recipe-maintainers:
    - skontar-altair
    - pczako-altair
