context:
  name: altair-aitools-runtime
  version: 1.2rc1
  python_min: "3.12"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://maven.rapidminer.com/repository/pypi-snapshot/packages/altair-aitools-runtime/${{ version }}/altair_aitools_runtime-${{ version }}.tar.gz
  sha256: 2978cecbf3cee41a07794b9208cc4ae632647c163803c9077e5d90143f2bba6c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
  - python ==${{ python_min }}
  - hatchling
  - pip
  run:
  - python >=${{ python_min }}
  - numpy >=1.24.4
  - packaging >=24.1
  - pandas >=2.0.3
  - pydantic >=2.0.3
  - rapidminer >=2024.1.0
  - websockets >=16.0
  - pyarrow >=19.0.1

tests:
  - python:
      imports:
        - altair_aitools.ext
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  summary: altair-aitools-runtime is a comprehensive package that provides a set of tools to run Altair RapidMiner AI tools extensions in Python.
  license: AGPL-3.0-only
  license_file: LICENSE
  homepage: https://altair.com/altair-rapidminer

extra:
  recipe-maintainers:
    - skontar-altair
    - pczako-altair
